name: 🚀 GKI_BUILD_OFFICIAL_METHOD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🧹 Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: 👨‍🔧 Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev libncurses5-dev x11proto-core-dev libxml2-utils xsltproc unzip python3 bc llvm lld clang lz4 repo
          curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -

      - name: ⏳ Repo Init & Sync (Official Branch)
        run: |
          mkdir gki_kernel && cd gki_kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b android15-6.6-2025-02 --depth=1
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle
          
          mkdir -p external/bazelbuild-rules_shell
          chmod +x tools/bazel
          chmod +x build/bazel.sh

      - name: 🔨 Build Kernel (Official Bazel Command)
        working-directory: gki_kernel
        run: |
          LTO=thin ./tools/bazel build --config=fast //common:kernel_aarch64_dist

      - name: 📦 Export Image
        run: |
          mkdir -p output
          cp gki_kernel/out/android15-6.6/dist/Image ./output/Image

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GKI-6.6.66-Official-Result
          path: output/Image
